### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by viditkulsh** [frypan05/png-to-pdf#1]
Your program to convert png to JPG is not visible/accessible on this repository.

**Comment by frypan05** [comment]
hey @viditkulsh ,
change the branch from Main to Master, you'll see the src directory in the codebase.

**Comment by viditkulsh** [comment]
Gotcha. 
Why not push src directory to your main branch too?

**Comment by frypan05** [comment]
Main branch is for a separate codebase that's currently on my local. But hey, soon.

**Comment by viditkulsh** [comment]
Dope!
